services:
  - type: web
    name: stripe-qbo-converter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: PORT
        value: 8000
